package com.example.b07project;

import android.os.Bundle;
import android.widget.Button;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import com.google.firebase.firestore.FirebaseFirestore;

public class ProviderReportActivity extends AppCompatActivity {

    private String childId;
    private String childName;
    private String providerId;
    private FirebaseFirestore db;
    private Spinner spinnerDateRange;
    private Button btnExportPDF;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_provider_report);

        // Get child info from intent
        childId = getIntent().getStringExtra("CHILD_ID");
        childName = getIntent().getStringExtra("CHILD_NAME");

        db = FirebaseFirestore.getInstance();

        // Get current provider ID from SharedPreferences or Firestore (TODO)
        providerId = getIntent().getStringExtra("PROVIDER_ID");

        // Initialize views
        TextView tvChildName = findViewById(R.id.tvChildName);
        tvChildName.setText("Report for: " + (childName != null ? childName : "Patient"));

        Button btnBack = findViewById(R.id.btnBack);
        btnBack.setOnClickListener(v -> finish());

        spinnerDateRange = findViewById(R.id.spinnerDateRange);
        spinnerDateRange.setSelection(2); // Default to "Last 30 Days"

        btnExportPDF = findViewById(R.id.btnExportPDF);
        btnExportPDF.setOnClickListener(v -> exportReportAsPDF());

        // Load report data
        loadReportData();
    }

    private void loadReportData() {
        // TODO: Fetch data from Firestore based on childId and date range
        // TODO: Query rescue_inhaler_logs, symptom_checkins, pef_readings, triage_sessions
        // TODO: Calculate metrics:
        //   - Rescue frequency count
        //   - Controller adherence %
        //   - Symptom burden (days with issues)
        //   - Zone distribution
        //   - Triage incident count

        // For now, display placeholder metrics
        TextView tvAdherenceDays = findViewById(R.id.tvAdherenceDays);
        tvAdherenceDays.setText("18 / 20");

        TextView tvProblemDays = findViewById(R.id.tvProblemDays);
        tvProblemDays.setText("5 days");

        TextView tvNightWaking = findViewById(R.id.tvNightWaking);
        tvNightWaking.setText("3 nights");
    }

    private void exportReportAsPDF() {
        // TODO: Generate PDF report with:
        //   - Child name and date range
        //   - Rescue frequency chart (time-series)
        //   - Controller adherence percentage
        //   - Zone distribution pie/bar chart
        //   - Symptom burden metrics
        //   - Notable triage incidents (if shared)
        //   - Footer with "Generated by SMART AIR" and date

        // For now, show a toast (TODO: implement PDF export with library like iTextPDF or similar)
        android.widget.Toast.makeText(this, "PDF export feature coming soon", android.widget.Toast.LENGTH_SHORT).show();
    }
}
